### ISSUE TITLE
可以与您交流取得联系吗？

### ISSUE THREAD

**Issue by johnsonwong666** [poboll/search_api#1]

**Comment by johnsonwong666** [comment]
部署vercel后 打开是404

**Comment by johnsonwong666** [comment]
有没有办法基于这些搜索的结果，去进行总结然后与用户进行问答呢？

**Comment by poboll** [comment]
宁好，此插件是一个模版可以为gpt镜像提供搜索结果建议。直接访问不会给出搜索结果，如下：
<img width="975" alt="image" src="https://github.com/poboll/poboll-api/assets/80184334/c826deec-764a-4fea-9ffa-cc61c5b9f54f">
需要提供搜索词以及条数。类似的：在vercel给出域名后面加入```/search?q=啊对对对是什么梗&max_results=3```
请注意，需要使用unicode解码工具，效果如下：
<img width="1814" alt="image" src="https://github.com/poboll/poboll-api/assets/80184334/7ecf7040-2e63-4627-86ed-e53301300175">

同时，可以搭配我的二开项目：https://github.com/poboll/ChatGPT-Next-Main
效果如下：
<img width="1342" alt="image" src="https://github.com/poboll/poboll-api/assets/80184334/ac1ec2d0-b853-4b65-b165-54bd8c3ee917">

私有化部署部署自己的镜像站，vercel的环境变量应配置为
```
OPENAI_API_KEY=<你的apikey密钥>
WEB_SEARCH_BASE_URL=<本插件部署在vercel的访问链接>
```
即可。希望能够解决你的问题～

镜像部署流程
1. 点击获取apikey [OpenAI API Key](https://platform.openai.com/account/api-keys);
2. 点击部署
   [![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fpoboll%2FChatGPT-Next-Main&env=OPENAI_API_KEY&env=WEB_SEARCH_BASE_URL&project-name=chatgpt-next-main&repository-name=ChatGPT-Next-Main),  `CODE` （可选）为网站访问密码
3. 尽情享受吧 :)
本二开仍在持续开发中，欢迎关注🌹

最后，求个star哇、祝好

**Comment by johnsonwong666** [comment]
感谢大佬开源，已star。

**Comment by johnsonwong666** [comment]
感觉搜索出来的结果，gpt不能很好的结合上下文， 并且无法总结搜出出来的内容，这是一个比较痛的点。
